OPENAI_API_KEY = "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"
WEATHER_API_KEY = "f5b0dd8ef5f71ac70e54a5d51eb85a9d"
WEATHERAPI_KEY = "52ba90cf47a24c469d2165131251606"
TOMORROWIO_API_KEY = "FCLY0kzI70SolDCk6V359wSS7mVankTT"
